layouts/_default/baseof.html, layouts/_default/list.html, layouts/_default/single.html, layouts/_default/terms.html, layouts/index.html, layouts/partials/footer.html, layouts/partials/head.html
1. If social is turned off - `feather.replace()` shouldn't be called.
2. Add missing closing tags.
3. Use `div` instead of `span` for item content in `index.html`. Spans could contain only inline elements, e.g. no `<p>` allowed.
Fixes #2
=> Fix html errors.

layouts/partials/header.html
Borrowed some code from https://github.com/gadenbuie/garrickadenbuie-com/blob/main/layouts/partials/head.html and blended it in. I hope the syntax is still valid and makes sense. I'm not sure if it ought to say `if isset .Site.Params "customCSS"` but I left it as `customcss` as you suggested.
=> Add custom CSS option - fixes issue #14

static/css/main.css
markdown:
```
* xxx
* yyy
1. aaa
2. bbb
3. ccc
```
before:
after:
=> fix unwanted star before nested ordered list

layouts/partials/header.html
The meta description tag is _allegedly_ important for SEO, and it can improve the page's summary in Google results.
=> Add support for meta descriptions

layouts/partials/header.html
@athul Sorry for the multiple PRs, I jumped the gun on the last one and wasn't really expecting such a fast turnaround on the original PR. 🤐  After looking into it more, it makes more sense to provide a custom meta description per-page where possible, so I copied the behavior of the `og:description` tag.
-----
Rather than use the same description on every page, prefer the post summary if it's available and only use .Params.description on the root page.
This mimics the behavior of the [opengraph internal template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/opengraph.html#L2) for the `og:description` tag.
=> Improve meta description

README.md, layouts/partials/head.html, layouts/partials/header.html, static/js/themetoggle.js
Added a dark/light mode toggle. This can be configured with `mode="toggle"` in `config.toml`. The default is light, and changes are saved in localStorage for persistence.
=> Add dark mode toggle

layouts/partials/header.html
This time the PR should be good 😄 
Currently the feather pack doesn't load if user doesn't put any link to their social media and set dark/light mode to "toggle", resulting in missing icon for theme switching. This commit fixes that by adding another condition for loading an icon pack.
=> fix for dark/light mode toggle when not using CDN

layouts/index.html, layouts/partials/header.html
Updated ```headers.html``` to allow <script> tags to be added to the ```<head>``` element, similar to [gokarna](https://github.com/526avijitgupta/gokarna).
```taml
[params]
mode="auto"
useCDN=false
subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
customJS = ["<script>console.log('JavaScript');</script>"]
```
Added the "readmore" class to the Read More links in the ```index.html``` page, they can then be styled separately from the other ```<a>``` elements. For example setting the border to be dotted:
=> Added <script> tag support and a readmore class to the readmore links

assets/css/main.css, layouts/partials/footer.html
Hello, I found that the width between icons in the latest footer is a bit too large. Also, when the mouse hovers over the icon, its shadow part will contain the padding on the right side, which is not beautiful.
So I made some changes and the changed footer is as follows.
=> chore: Change CSS for Socials in Footer again

assets/css/fonts.css
I added the `font-display` descriptor with the `swap` value to ensure that fonts are not blocking, i.e., text is shown instantly, even on slow connections.
=> Add font swapping

assets/css/main.css
=> Fixed title and menu links overlap in header

layouts/partials/head.html
Changing the theme using toggle does not require reloading the entire page using self-linking
=> fix: no need to reload for theme change

layouts/index.html, layouts/partials/pagedescription.html
This change breaks out the page description from the 'index.html' layout into its own partial - I'm using this on my blog to change the way the description is rendered without having to alter the theme itself.
=> Break out the page description from the 'index.html' layout

layouts/index.html
`Read more --> ` element is gone by #71. so i fixed to display again.
ref: https://github.com/athul/archie/issues/72
=> Fix: display `Read more -->`

README.md, layouts/partials/header.html
Use `mathjax = true` or `katex = true` to enable either mathjax or katex
Closes #74
=> Add mathjax and katex support

exampleSite/config.toml
Looks like there's a copy-and-paste error in the example site's `config.toml`, as the Twitter link currently points to GitHub with an invalid username.
=> Fix Twitter link in example site footer

README.md, layouts/partials/footer.html
`google_analytics_async.html` is now removed from Hugo and the regular template should be used.
Hugo pull-request: [#12299](https://github.com/gohugoio/hugo/pull/12299)
Without this change, it is not possible to build with Hugo v0.125.0 or later.
=> Fix compatibility with Hugo v0.125.0

layouts/_default/list.html, layouts/_default/single.html, layouts/_default/term.html, layouts/index.html
":date_medium" matches "Jan 2, 2006" in english locales while adapting to hugo's configured locale.
=> Use locale-aware alias for date formatting

README.md, assets/css/dark.css, assets/css/main.css, exampleSite/content/posts/post-6.md, layouts/shortcodes/callout.html
Expand the callout functionality to allow for a base set of callout types which include:
* alert
* custom
* tip
* warning
Related to https://github.com/athul/archie/issues/106.
Tested by building the local example website
New light-mode:
---
New dark-mode:
=> Expand callouts functionality

layouts/partials/head.html
Update title to use `absLangURL` instead of `absURL` in order to correctly navigate to translated home page.
=> Multilingual Aware Title Link

layouts/_default/single.html
```
https://github.com/athul/archie?tab=readme-ov-file#writing-posts
toc: true/false (optional)
```
It says here that the value of “toc” can be either true or false, and in fact, even if it is false, the TOC will still be displayed on the page. 
The previous code only determines whether to display “toc” by whether it is defined or not, It should also be determined whether its value is true.
=> Fixed a bug
